apiVersion: apps/v1
kind: Deployment
metadata:
  name: arx
  namespace: default
  labels:
    app: arx
    tier: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arx
  template:
    metadata:
      labels:
        app: arx
    spec:
      containers:
        - name: arx-pod
          image: jtovartr/python3.7:v1
          command:
            - bash
            - "-c"
            - python3.7 arx.py
          volumeMounts:
            - mountPath: /mount
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /home/jesus/Escritorio/privacy-manager/mounts/arx
            # this field is optional
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: arx
  namespace: default
spec:
  selector:
    app: arx
  ports:
    - port: 8083
      targetPort: 8083
  clusterIP: ${ARX}
