---
apiVersion: extensions/v1beta1
#apiVersion: networking.k8s.io/v1

kind: Ingress
metadata:
  name: phpmyadmin-http-ingress
  labels:
    app: phpmyadmin
spec:
  backend:
    serviceName: phpmyadmin-service
    servicePort: 80
