apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv
  namespace: default
  labels:
    app: priv
    tier: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priv
  template:
    metadata:
      labels:
        app: priv
    spec:
      containers:
        - name: priv-pod
          image: roxax19/nodejs:0.3
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/node/mount/ssl/myCA.pem"
          command:
            - bash
            - "-c"
            - node priv.js
          volumeMounts:
            - mountPath: /node/mount
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /home/jesus/Escritorio/privacy-manager/mounts/priv
            # this field is optional
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: priv
  namespace: default
spec:
  selector:
    app: priv
  ports:
    - port: 8082
  clusterIP: ${PRIV}
