apiVersion: v1
kind: Service
metadata:
  name: mongo-0
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    mysql: mongoMaster
  clusterIP: ${MONGODB_0}
