apiVersion: apps/v1
kind: Deployment
metadata:
  name: priv-mongo
  namespace: default
  labels:
    app: priv-mongo
    tier: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priv-mongo
  template:
    metadata:
      labels:
        app: priv-mongo
    spec:
      containers:
        - name: priv-mongo-pod
          image: jtovartr/nodejs_prueba
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: "/node/mount/ssl/myCA.pem"
          command:
            - bash
            - "-c"
            - node priv-mongo.js
          volumeMounts:
            - mountPath: /node/mount
              name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /home/jesus/Escritorio/privacy-manager/mounts/mongodb
            # this field is optional
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: priv-mongo
  namespace: default
spec:
  selector:
    app: priv-mongo
  ports:
    - port: 8081
  type: LoadBalancer
  clusterIP: ${PRIV_MONGO}
